// Generated by scripts/generate-page-builder-catalog.ts — do not edit by hand.
// Titles and descriptions are shadcncraft's own; Jev reads them to choose a
// variant, so a variant that keeps being misread is fixed upstream or here in
// the generator, not in this file.

export type PageBlockVariant = {
  id: string
  title: string
  description: string
}

export const PAGE_BLOCK_VARIANTS: Record<string, PageBlockVariant[]> = {
  "activity-feed": [
    {
      id: "activity-feed-1",
      title: "Filterable timeline with inline context",
      description:
        "A chronological activity feed presented as a vertical timeline, combining user avatars, action summaries, and timestamps for quick scanning. Includes a top search field and segmented filters to switch between activity types. The layout adapts cleanly to smaller screens by tightening spacing and stacking controls while preserving the same linear reading order.",
    },
  ],
  "ai-insights": [
    {
      id: "ai-insights-1",
      title: "AI insights",
      description:
        "Alerts and opportunities surfaced automatically across the funnel.",
    },
  ],
  "attribution-breakdown": [
    {
      id: "attribution-breakdown-1",
      title: "Attribution breakdown",
      description:
        "Revenue credited by first touch vs last touch, per channel.",
    },
  ],
  benefits: [
    {
      id: "benefits-1",
      title: "Alternating rows with text and image",
      description:
        "A benefits section with a headline and intro, followed by multiple feature rows that alternate text and visual previews. Each row includes an icon, feature title, short description, bullet points, and a supporting UI image. Use to explain a product's core value areas in a structured, scannable way on landing pages.",
    },
    {
      id: "benefits-2",
      title: "Alternating rows with actions and image",
      description:
        "A benefits section with a headline and intro, followed by multiple feature cards arranged in a staggered grid. Each card includes an icon, feature title, short description, supporting UI image, and primary actions. Use to present key product capabilities when you want each feature to stand alone and drive clicks to demos or deeper pages.",
    },
    {
      id: "benefits-3",
      title: "Stacked sections with full-bleed media",
      description:
        "A benefits section with a headline and intro, followed by stacked feature sections that alternate text and large visual panels. Each feature includes a title, short description, bullet points, and a strong illustrative image. Use when you want to tell a more visual, narrative story around key product benefits rather than drive quick scanning or clicks.",
    },
    {
      id: "benefits-4",
      title: "Compact icon list",
      description:
        "A simple benefits block that displays a small set of features as icon-led items with short titles and descriptions. Use when you need to quickly communicate core value points without images, interactions, or deep explanation, such as secondary sections or lower on a page.",
    },
    {
      id: "benefits-5",
      title: "Icon grid",
      description:
        "A benefits block with a headline and short intro, followed by a grid of icon-led features arranged in two rows. Each item includes an icon, feature name, and short description. Use to present a broad set of product benefits at a glance without visuals or calls to action.",
    },
    {
      id: "benefits-6",
      title: "Image-led cards",
      description:
        "A benefits block with a headline and short intro, followed by large visual feature cards. Each card pairs a strong image with a feature title and short description. Use when visuals are doing most of the work and you want to communicate product value through imagery rather than text-heavy explanations.",
    },
    {
      id: "benefits-7",
      title: "Split highlights with supporting list",
      description:
        "A benefits block with a headline and intro, followed by two primary feature highlights with large images. Secondary benefits are listed below as a compact icon-and-text row. Use when you want to spotlight a small number of hero features while still covering supporting capabilities in the same section.",
    },
    {
      id: "benefits-8",
      title: "Hero media with supporting list",
      description:
        "A benefits block with a headline and intro, followed by a single large hero image. Supporting benefits are listed below as icon-led items with short descriptions. Use when you want a strong visual anchor with concise, secondary benefit details for quick scanning.",
    },
    {
      id: "benefits-9",
      title: "Two-column text layout",
      description:
        "A benefits block with a strong headline and supporting text split across two columns. Use to clearly explain a single core value or positioning statement when you need more depth than a short tagline but no visuals or feature lists.",
    },
    {
      id: "benefits-10",
      title: "Full-width media with overlay text",
      description:
        "A benefits block built around a large, full-width image with short text overlaid directly on the visual. Use to make a single, emotionally driven point where the image carries most of the meaning and the copy reinforces one clear benefit.",
    },
    {
      id: "benefits-11",
      title: "Emphasized lead with supporting column",
      description:
        "A benefits block with a strong headline on the left and a longer supporting explanation on the right, with a clear visual hierarchy between primary and secondary text. Use to reinforce a core positioning message when you want one idea to land clearly without images or feature lists.",
    },
    {
      id: "benefits-12",
      title: "Two-column icon list",
      description:
        "A two-column layout that displays a list of items, each paired with an icon, title, and short description. Items flow vertically within each column and adapt to a single column on smaller screens. Use when you need a dense but scannable list with clear visual anchors.",
    },
    {
      id: "benefits-13",
      title: "Card grid with section header",
      description:
        "A layout with a section header followed by a grid of equal-height cards. Each card includes an icon, title, and short text, arranged in a consistent grid that collapses responsively. Use when you need a structured, repeatable set of items with strong visual separation.",
    },
  ],
  "blog-listing": [
    {
      id: "blog-listing-1",
      title: "Featured grid",
      description:
        'A responsive blog listing that highlights recent posts in a clean card grid. Includes category, title, read time, author, and date, with a clear section header and optional "See all" action. Works well for homepages or content hubs where you want to surface a small set of featured articles.',
    },
    {
      id: "blog-listing-2",
      title: "Paginated card grid",
      description:
        'A card-based blog layout with a clear section header and a progressive "Load more" pattern. Uses consistent post cards with image, category, title, meta, and author, designed to scale as content grows. Suitable for blog index pages or homepages that need a lightweight, expandable feed without full pagination.',
    },
    {
      id: "blog-listing-3",
      title: "Featured lead with supporting grid",
      description:
        "A blog layout anchored by a large featured post followed by a compact card grid. Emphasizes editorial hierarchy by spotlighting a primary article, then surfacing recent or related posts underneath. Works well for blog homepages where one story should lead, with the rest supporting discovery and ongoing reading.",
    },
    {
      id: "blog-listing-4",
      title: "Dense editorial grid",
      description:
        "A high-density card grid that surfaces many posts at once with equal visual weight. Uses consistent card sizing and rhythm to support fast scanning and browsing. Best for archive pages or content hubs where breadth and discovery matter more than a single featured story.",
    },
  ],
  "campaign-performance": [
    {
      id: "campaign-performance-1",
      title: "Campaign performance",
      description: "Top campaigns by leads generated, as a compact data table.",
    },
  ],
  careers: [
    {
      id: "careers-1",
      title: "Job list with metadata",
      description:
        "A simple vertical job list focused on clarity and scannability. Uses a single-column layout with clear role titles and lightweight metadata like location, work type, and salary. Designed to help users quickly compare openings and jump into a role without visual noise.",
    },
    {
      id: "careers-2",
      title: "Job list with media lead",
      description:
        "A split layout that pairs a job list with a large supporting image. Uses the image to set tone and culture, while keeping roles and metadata clean and easy to scan alongside it. Suitable for careers landing pages where brand and roles need equal weight.",
    },
    {
      id: "careers-3",
      title: "Card grid job listings",
      description:
        "A multi-column grid of role cards with consistent metadata and actions. Designed for scanning and comparison across roles, with equal visual weight and clear hierarchy. Works well for larger job sets where breadth matters more than storytelling.",
    },
    {
      id: "careers-4",
      title: "Feature image with list",
      description:
        "A careers layout anchored by a large lifestyle image, followed by a clean vertical job list. Uses imagery to set culture and tone first, then supports focused role scanning. Best when you want to sell the team and environment before the openings.",
    },
    {
      id: "careers-5",
      title: "Split intro with stacked listings",
      description:
        "A careers layout with a left-aligned intro and a dense, stacked job list alongside it. Prioritizes fast scanning of roles over storytelling. Best for teams with multiple open positions where clarity and comparison matter more than brand imagery.",
    },
  ],
  "channel-performance": [
    {
      id: "channel-performance-1",
      title: "Channel performance",
      description:
        "Clicks received vs leads converted, by channel, as grouped bars.",
    },
  ],
  checkout: [
    {
      id: "checkout-1",
      title: "Checkout page with shipping, payment and order summary",
      description:
        'A comprehensive and professional checkout interface featuring a dual-column layout. The left column is dedicated to user data entry, the right column acts as a fixed "Summary" sidebar, providing a final review of cart items, detailed cost breakdowns (subtotal, shipping, taxes), and the primary action button.',
    },
    {
      id: "checkout-2",
      title: "Modular checkout with summary and overview sidebars",
      description:
        'Checkout interface that uses a multi-card layout to prioritize order transparency. It features a "Summary" of items and an "Overview" of costs (including a promo code field) on the left side, while the more extensive "Shipping Information" and "Payment" forms are grouped in a primary card on the right. This arrangement allows users to keep their order details constantly in sight while navigating through the data entry process.',
    },
    {
      id: "checkout-3",
      title: "Checkout with left-aligned order overview and payment stack",
      description:
        'A checkout layout that separates order details from data entry through a clean, vertical split. The left column is dedicated to a high-visibility "Summary" of cart items and a secondary "Overview" card for financial totals and promo codes. The right side contains the primary "Shipping Information" and "Payment" sections, using a vertically stacked form design that maintains a clear, linear path for the user to complete their purchase.',
    },
  ],
  contact: [
    {
      id: "contact-1",
      title: "Centered form, single-column",
      description:
        "A centered contact form with a clear headline and stacked inputs. Uses a simple, linear flow that keeps focus on completion. Best for general inquiries where you want minimal distraction and a calm, neutral presentation.",
    },
    {
      id: "contact-2",
      title: "Centered form in card",
      description:
        "A centered contact form wrapped in a card with clear visual boundaries. The card adds emphasis and contrast while keeping the layout simple and focused. Good when the form should feel contained and slightly elevated from the page background.",
    },
    {
      id: "contact-3",
      title: "Split form with image",
      description:
        "A two-column layout pairing a contact form with a large supporting image. The image adds personality and visual balance while the form stays clear and readable. Works well when you want the contact section to feel more human and less transactional.",
    },
    {
      id: "contact-4",
      title: "Multi-channel contact options",
      description:
        "A centered layout that surfaces multiple ways to get in touch without a form. Uses icon-led contact methods laid out horizontally, with clear labels and availability details. Best when you want to push people to the right channel fast rather than collect messages.",
    },
    {
      id: "contact-5",
      title: "Global presence with contact methods",
      description:
        "A wide, visual-first layout that pairs a world map with key contact channels. Uses location markers to signal global reach, with email, phone, and live chat grouped below for quick access. Good for companies that want to show scale or multiple offices without pushing a form.",
    },
    {
      id: "contact-6",
      title: "Map-first contact",
      description:
        "A contact layout built around a large location map, with clear contact methods shown below and in a compact side panel. Works well for businesses with a physical presence where location and availability matter as much as the form itself.",
    },
    {
      id: "contact-7",
      title: "Image-led contact",
      description:
        "A contact layout anchored by a large, friendly image, with key contact options displayed clearly below and in a side panel. Good for brands that want to feel personal and approachable without using a full form upfront.",
    },
    {
      id: "contact-8",
      title: "Hero image with channel cards",
      description:
        "A contact layout that pairs a large, edge-to-edge image with stacked contact channels. The image creates visual weight at the top, while card-based options below make it easy to scan and choose how to get in touch. Works well when you want a strong visual anchor without using a form.",
    },
    {
      id: "contact-9",
      title: "Centered CTA panel",
      description:
        "A minimal contact block built around a single, centered call to action. Uses a contained panel with clear hierarchy and one primary button, making it ideal for low-friction contact moments at the end of a page or between sections.",
    },
    {
      id: "contact-11",
      title: "Centered form with supporting sidebar",
      description:
        "A balanced contact layout with a primary, centered form and a secondary sidebar that mirrors or reinforces the same interaction. The main column keeps focus on the form, while the sidebar provides a persistent fallback or alternative entry point. Useful when you want a calm, symmetrical layout with built-in redundancy for conversion.",
    },
  ],
  "cost-per-acquisition-trend": [
    {
      id: "cost-per-acquisition-trend-1",
      title: "Cost per acquisition trend",
      description:
        "Daily cost per acquisition as an area trend with period comparison.",
    },
  ],
  cta: [
    {
      id: "cta-1",
      title: "Centered headline with stacked actions",
      description:
        "A centered call to action with a strong headline, short supporting copy, and side-by-side buttons. The layout feels more editorial and blends naturally into content-heavy pages. Works well when the CTA should feel integrated rather than isolated.",
    },
    {
      id: "cta-2",
      title: "Left-aligned headline with inline actions",
      description:
        "A left-aligned call to action with a strong headline, short supporting copy, and side-by-side buttons. The layout feels more editorial and blends naturally into content-heavy pages. Works well when the CTA should feel integrated rather than isolated.",
    },
    {
      id: "cta-3",
      title: "High-contrast panel with stacked actions",
      description:
        "A bold, high-contrast CTA presented inside a contained panel, with a centered headline and stacked primary and secondary actions. The strong visual separation makes this ideal for end-of-page moments where the CTA should clearly stand apart from surrounding content.",
    },
    {
      id: "cta-4",
      title: "High-contrast panel with left-aligned actions",
      description:
        "A wide, high-contrast CTA panel with left-aligned content and inline primary and secondary actions. The asymmetric layout creates a strong visual anchor while leaving room for surrounding content, making it well suited for mid-page transitions or section breaks.",
    },
    {
      id: "cta-5",
      title: "Split content with feature list and media",
      description:
        "A two-column CTA layout combining structured text and a visual panel. Uses a feature list to add scannability and depth, paired with a supporting image or illustration. Works well when the CTA needs a bit more explanation without becoming a full section.",
    },
    {
      id: "cta-6",
      title: "Feature-led split with primary visual",
      description:
        "A split CTA layout anchored by a dominant visual panel, with supporting copy and a short feature list alongside. Emphasizes imagery first, then reinforces the action with structured text and clear primary and secondary buttons. Suitable when visual tone or brand feel needs to carry more weight than the copy.",
    },
    {
      id: "cta-7",
      title: "Product preview split with feature checklist",
      description:
        "A split CTA layout that pairs structured copy and a short feature list with a live product preview or dashboard screenshot. The layout leads with value explanation, then reinforces credibility through a concrete UI example. Works well when showing real product depth without turning the section into a full feature block.",
    },
    {
      id: "cta-8",
      title: "Wide product panel with offset preview",
      description:
        "A wide, left-aligned CTA paired with a large, offset product screenshot that bleeds toward the edge of the container. The layout creates a sense of depth and scale, making the product feel substantial while keeping the call to action simple and focused. Good for high-confidence CTAs where the UI itself does most of the convincing.",
    },
  ],
  "customer-health-score": [
    {
      id: "customer-health-score-1",
      title: "Customer health score",
      description: "Average customer health as an arc gauge with score bands.",
    },
  ],
  "deal-velocity-by-segment": [
    {
      id: "deal-velocity-by-segment-1",
      title: "Deal velocity",
      description: "Average days in stage by segment as a heatmap.",
    },
  ],
  "deals-table": [
    {
      id: "deals-table-1",
      title: "Deals table",
      description: "Open deals with owner, stage, value, and close date.",
    },
  ],
  "engagement-by-day-hour": [
    {
      id: "engagement-by-day-hour-1",
      title: "Engagement by day & hour",
      description: "Open-rate heatmap by send day and hour.",
    },
  ],
  faqs: [
    {
      id: "faqs-1",
      title: "Grid FAQs with CTA",
      description:
        "Multi-column FAQ layout with short answers visible by default. Includes an optional CTA panel below. Scales down to a stacked list on mobile.",
    },
    {
      id: "faqs-2",
      title: "Accordion list with centered CTA",
      description:
        "Single-column, centered accordion for longer answers. Optimized for reading and scanning. Collapses into a stacked accordion on mobile.",
    },
    {
      id: "faqs-3",
      title: "Wide accordion with stacked mobile preview",
      description:
        "A responsive FAQ section with a wide, centered accordion for desktop, plus a compact stacked version shown as a mobile preview. Built for clean scanning, with one expanded answer and the rest collapsed by default.",
    },
    {
      id: "faqs-4",
      title: "Centered accordion with supporting panel",
      description:
        "A clean, centered FAQ accordion paired with a narrow sidebar version. Uses a strong section header and clear dividers for easy scanning, with an optional support link at the end. Works well for product or marketing pages where FAQs are a secondary section, not the main focus.",
    },
  ],
  footer: [
    {
      id: "footer-1",
      title: "Multi-column sitemap footer",
      description:
        "A wide, multi-column footer with grouped navigation links and a compact legal row. Designed for content-heavy sites that need clear link categorization and quick scanning. Includes a stacked variant for mobile layouts.",
    },
    {
      id: "footer-2",
      title: "Sitemap footer with newsletter signup",
      description:
        "A multi-column sitemap footer with a prominent newsletter signup band. Combines navigation, legal links, and email capture in a single layout. Designed for marketing sites that want to convert at the page end, with a stacked mobile layout that prioritizes the signup first.",
    },
    {
      id: "footer-3",
      title: "Compact sitemap footer",
      description:
        "A clean, low-profile sitemap footer with evenly spaced link columns and a minimal brand and legal row. Designed for content-heavy sites that need clear navigation without visual weight. Collapses into a single stacked list on mobile for fast scanning.",
    },
    {
      id: "footer-4",
      title: "Brand-led sitemap footer",
      description:
        "A sitemap footer anchored by a short brand statement and logo, followed by structured link columns and legal links. Gives more context about the company while keeping navigation clear. Works well for marketing sites where brand positioning matters as much as wayfinding.",
    },
  ],
  "goal-progress": [
    {
      id: "goal-progress-1",
      title: "Goal progress",
      description:
        "Month-to-date attainment against monthly targets as bullet bars.",
    },
  ],
  hero: [
    {
      id: "hero-1",
      title: "Centered headline with media hero",
      description:
        "A classic centered hero with a strong headline, short supporting copy, and a primary call to action. Anchored by a large visual or video to set tone and establish brand presence. Works well as a primary landing hero when you want clarity first and visual impact second.",
    },
    {
      id: "hero-2",
      title: "Full-bleed background with centered content",
      description:
        "A bold, immersive hero that places the headline and call to action directly on a full-bleed visual background. Designed to create mood and instant impact, with social proof reinforcing credibility. Best used when you want an emotional first impression and strong brand presence right at the top.",
    },
    {
      id: "hero-3",
      title: "Light background with centered content",
      description:
        "A calm, airy hero that centers the headline and call to action over a soft, low-contrast background. Designed to feel open and approachable, with social proof placed directly beneath the primary action. Works well for product-led sites that want clarity and reassurance without heavy visual weight.",
    },
    {
      id: "hero-4",
      title: "Soft gradient hero with dual CTAs and rating",
      description:
        "A centered hero set on a subtle gradient background, using stacked CTAs to support different commitment levels. Includes lightweight credibility with an inline rating, making it well suited to waitlists, previews, or early-access launches where trust and softness matter more than urgency.",
    },
    {
      id: "hero-5",
      title: "Split layout with waitlist capture",
      description:
        "A balanced split hero that pairs left-aligned messaging with a strong visual on the right. Uses an inline email field and single primary CTA to support early-access or waitlist flows. Works well when the image carries mood or concept, while the layout keeps conversion front and center without feeling heavy.",
    },
    {
      id: "hero-6",
      title: "Feature-led split hero",
      description:
        "A practical split hero that pairs a strong visual with a short benefits list. Designed to quickly explain value through scannable points, with a clear primary CTA. Works well for product-led pages where clarity and speed to understanding matter more than mood alone.",
    },
    {
      id: "hero-7",
      title: "Editorial story hero",
      description:
        "A narrative-led hero that explains the problem before selling the solution. Uses longer-form copy, author attribution, and a strong visual to build trust and context. Best suited to thought leadership, launch posts, or product pages where education and credibility come before conversion.",
    },
    {
      id: "hero-8",
      title: "Minimal page header",
      description:
        "A stripped-back hero for secondary pages. Focuses on a clear page title, short supporting copy, and a simple primary action. Best for pricing, docs, feature detail pages, or anywhere the goal is clarity over impact.",
    },
    {
      id: "hero-9",
      title: "Page header with supporting visual",
      description:
        "A balanced hero that pairs a clear page title and primary actions with a strong supporting image. Works well when you want more visual context than a minimal header, without going full marketing hero. Ideal for feature overviews, product detail pages, or campaign landing pages where clarity still comes first.",
    },
    {
      id: "hero-10",
      title: "Full-bleed image hero",
      description:
        "A bold, image-led hero with text overlaid on photography. Best when you want an emotional hook first and the message second. Works well for marketing pages, brand stories, and team or culture-led sections where the image does most of the work.",
    },
  ],
  "hero-time-series": [
    {
      id: "hero-time-series-1",
      title: "Hero time series",
      description:
        "Hero area chart comparing this period against the previous period.",
    },
  ],
  "lead-to-customer-funnel": [
    {
      id: "lead-to-customer-funnel-1",
      title: "Lead-to-customer funnel",
      description: "Marketing-to-sales handoff as concentric ring progress.",
    },
  ],
  "leads-by-region": [
    {
      id: "leads-by-region-1",
      title: "Leads by region",
      description:
        "Leads and pipeline value by country, with list and map views.",
    },
  ],
  "marketing-funnel": [
    {
      id: "marketing-funnel-1",
      title: "Marketing funnel",
      description: "Stage-by-stage conversion across the marketing funnel.",
    },
  ],
  "metric-cards": [
    {
      id: "metric-cards-1",
      title: "Metric cards",
      description:
        "Four key metrics in a single strip: spend, revenue, cost per lead, and conversion rate.",
    },
  ],
  metrics: [
    {
      id: "metrics-1",
      title: "Wide stats row with geographic backdrop",
      description:
        "A horizontally distributed metrics layout that pairs large headline numbers with short labels, anchored by a subtle world map background. The pattern emphasizes scale and credibility without heavy visuals. On mobile, the metrics collapse into a vertical list, keeping each stat easy to scan while preserving hierarchy.",
    },
    {
      id: "metrics-2",
      title: "Centered headline with inline stat columns",
      description:
        "A metrics layout built around a strong centered heading, followed by evenly spaced stat columns with short supporting labels and optional inline links. The pattern emphasizes balance and readability, using clear vertical dividers to separate each metric. On mobile, the stats stack into a single-column list while keeping the headline and hierarchy intact.",
    },
    {
      id: "metrics-3",
      title: "Split content with media anchor",
      description:
        "A two-column metrics layout that pairs a text-led stats group with a strong visual anchor. The pattern uses a left-aligned heading and compact metric blocks, balanced by a fixed-aspect image on the opposite side to create visual weight. On mobile, the image drops below the metrics and the stats stack vertically, preserving hierarchy and scanability.",
    },
    {
      id: "metrics-4",
      title: "Centered headline with inline stat row",
      description:
        "A symmetric metrics layout built around a centered headline and a single horizontal row of key stats. Each metric is evenly spaced to create a calm, balanced rhythm and equal visual weight. The pattern emphasizes comparability and quick scanning. On mobile, the metrics stack vertically into a single column while keeping the headline centered to maintain hierarchy and focus.",
    },
    {
      id: "metrics-5",
      title: "Carded metrics row",
      description:
        "A metrics layout where each stat is wrapped in a lightweight card. The cards create clear boundaries, making each metric feel discrete and scannable while still reading as a group. The pattern works well when metrics need visual emphasis without heavy decoration. On mobile, cards stack vertically with consistent spacing, preserving rhythm and hierarchy.",
    },
    {
      id: "metrics-6",
      title: "Inline metrics with dividers",
      description:
        "A single-row metrics layout that uses subtle vertical dividers instead of cards. This keeps the section feeling light and flat while still giving each metric clear separation. Works well when metrics are supporting evidence rather than the main focal point. On smaller screens, the metrics stack into a clean vertical list with the same divider rhythm preserved.",
    },
    {
      id: "metrics-7",
      title: "Inline stats row with optional links",
      description:
        "A centered section header paired with a single horizontal row of key stats. Uses generous whitespace and consistent column widths to make the numbers feel calm and easy to scan. On smaller screens, the row collapses into a clean vertical stack without changing the overall rhythm.",
    },
  ],
  "newsletter-signup": [
    {
      id: "newsletter-signup-1",
      title: "Split layout with visual anchor",
      description:
        "A newsletter signup pattern that pairs a simple email capture with a strong visual anchor. The form stays lightweight and prominent, while the adjacent product visual adds context and credibility. On smaller screens, the layout stacks to keep the signup action clear and friction-free.",
    },
    {
      id: "newsletter-signup-2",
      title: "Value-led signup with supporting bullets",
      description:
        "A newsletter signup pattern that leads with clear value before the email field. Short bullet points set expectations and reduce hesitation, while the form remains simple and easy to scan. The supporting visual reinforces product context without competing with the primary signup action, and the layout stacks cleanly on smaller screens.",
    },
    {
      id: "newsletter-signup-3",
      title: "Inline headline with minimal form",
      description:
        "A compact newsletter signup pattern that places the email field inline with the headline. The layout minimizes friction and keeps attention focused on a single action, making it suitable for low-commitment sections or repeated placements. On smaller screens, the form stacks cleanly while preserving hierarchy and clarity.",
    },
    {
      id: "newsletter-signup-4",
      title: "Centered call to action with supporting microcopy",
      description:
        "A centered newsletter signup pattern that emphasizes balance and clarity. The headline and form are vertically stacked to create a clear focal point, with supporting microcopy reinforcing trust without competing for attention. The layout works well as a primary conversion section and scales cleanly to mobile by preserving alignment and spacing.",
    },
    {
      id: "newsletter-signup-5",
      title: "Inline callout with contained form",
      description:
        "A horizontal newsletter signup pattern presented inside a soft container to separate it from surrounding content. The headline and description anchor the left side while the inline form sits to the right, creating a clear scan path and compact footprint. Works well as an embedded callout within long pages and collapses cleanly to a stacked layout on smaller screens.",
    },
  ],
  "paid-media-allocation": [
    {
      id: "paid-media-allocation-1",
      title: "Paid media allocation",
      description: "Donut breakdown of spend across paid channels.",
    },
  ],
  "pipeline-by-stage": [
    {
      id: "pipeline-by-stage-1",
      title: "Pipeline by stage",
      description:
        "Open pipeline value and share across deal stages as a funnel.",
    },
  ],
  pricing: [
    {
      id: "pricing-1",
      title: "Three-tier card pricing grid",
      description:
        "A classic three-column pricing layout with equal-weight plan cards for easy comparison. Each card follows the same vertical rhythm with plan name, price, primary action, and feature list, making differences scannable at a glance. The pattern scales cleanly to mobile as a horizontal carousel or stacked cards, keeping one plan in focus at a time.",
    },
    {
      id: "pricing-2",
      title: "Focused two-plan comparison",
      description:
        "A simplified pricing layout that presents two plans side by side to reduce choice overload. The shared header anchors context, while the paired cards make differences easy to scan without overwhelming the user. This pattern works well when offerings are intentionally limited or when you want to guide users toward a primary upgrade path, and it adapts cleanly to a swipeable carousel on smaller screens.",
    },
    {
      id: "pricing-3",
      title: "Single plan spotlight",
      description:
        "A centered, single-card pricing layout that puts all attention on one plan. Removing comparisons reduces decision friction and works well for early-stage products, default plans, or checkout-focused pages. The pattern scales cleanly by adding secondary plans later without changing the core structure.",
    },
    {
      id: "pricing-4",
      title: "Three-plan comparison with highlighted default",
      description:
        'A classic three-tier pricing layout with a clearly emphasized middle plan to guide choice. The visual weight, border treatment, and "most popular" marker steer users toward a recommended option while still allowing easy comparison. Works well when you want flexibility without overwhelming the decision.',
    },
    {
      id: "pricing-5",
      title: "Side-by-side plans with duplicated emphasis",
      description:
        "A two-plan layout where one option is visually emphasized through stronger borders and hierarchy, even when the plans are similar. This pattern is useful for steering users toward a preferred choice while still showing a clear alternative, without introducing extra complexity or tiers.",
    },
    {
      id: "pricing-6",
      title: "Single-plan focused pricing",
      description:
        "A minimal pricing pattern that centers on a single plan, removing comparison to reduce decision friction. This works well when there is only one offering, or when you want to validate pricing without distracting users with alternatives.",
    },
    {
      id: "pricing-7",
      title: "Feature-comparison table pricing",
      description:
        "A dense pricing pattern that pairs plans with a side-by-side feature matrix. This works when buyers need to evaluate capability differences in detail and are willing to scan vertically to compare limits, access levels, and inclusions across tiers.",
    },
  ],
  "product-category": [
    {
      id: "product-category-1",
      title: "Category navigation grid with immersive hero imagery",
      description:
        "A visually driven category section featuring a three-column grid. Each card uses large, high-impact photography as a background, with the category title and a brief descriptive subtext positioned in the bottom-left corner. This layout is designed to inspire users through lifestyle imagery",
    },
    {
      id: "product-category-2",
      title: "Category grid with external labels",
      description:
        "A minimalist category navigation section featuring a balanced three-column grid. Unlike overlay styles, this layout places category titles and descriptive subtext directly below each image, ensuring maximum legibility. Using high-quality lifestyle and product photography, it provides a professional and airy entry point to specific store sections.",
    },
    {
      id: "product-category-3",
      title: "Asymmetric category grid with mixed card orientations",
      description:
        "A visually engaging category section featuring an asymmetric three-column layout. The left column showcases a large, vertical hero image for while the right side is split into two stacked horizontal cards. This varied grid structure creates a modern, editorial feel that emphasizes priority collections through size while maintaining a clean and organized aesthetic with bottom-aligned text overlays.",
    },
    {
      id: "product-category-4",
      title: "Inverted asymmetric grid with top-aligned hero card",
      description:
        'A dynamic category section featuring an asymmetric three-card grid. The layout highlights "New Arrivals" with a large, full-width horizontal hero card at the top, while "Accessories" and "Last Pieces" are displayed in two smaller, side-by-side cards below. All categories utilize immersive photography with bottom-left text overlays, creating a modern and editorial navigation experience.',
    },
    {
      id: "product-category-5",
      title: "vertical category grid with labels",
      description:
        "A clean and balanced category section featuring a four-column grid of tall, vertical cards. Each card uses high-impact photography with a subtle dark gradient at the bottom to enhance the legibility of the centered white labels. This layout is ideal for stores with multiple key departments, providing a uniform and highly structured entry point to the entire collection.",
    },
  ],
  "product-details": [
    {
      id: "product-details-1",
      title: "Product overview with configuration",
      description:
        "A clean and professional product detail section featuring a large primary image on the left and functional configuration tools on the right. The information hierarchy includes the product title, star ratings, price, and a brief description. Below, users can interact with size selection tiles, color swatches, and a quantity selector before adding the item to the cart. This layout is designed for maximum clarity, guiding the user through the customization process toward a final purchase.",
    },
    {
      id: "product-details-2",
      title: "Product page with breadcrumbs and accordion",
      description:
        "A comprehensive product layout featuring a top breadcrumb navigation for easy store browsing. The left side showcases a large product image, while the right side organizes purchase details: rating, price, size tiles, and color swatches. Below the primary button, a vertical accordion provides detailed information keeping the page clean while offering deep product insights.",
    },
    {
      id: "product-details-3",
      title: "Detailed product view with specifications and gallery",
      description:
        "A content-rich product detail section that prioritizes technical information. The layout features a primary text area on the left detailing fabric composition and design features, balanced by a configuration sidebar on the right for size and color selection. Below, a four-column gallery showcases the product in every available color variant, providing a visual overview that aids the customer's final decision.",
    },
    {
      id: "product-details-4",
      title: "Product detail page with vertical thumbnail gallery",
      description:
        "A streamlined product section featuring a multi-image navigation system. The layout includes a vertical column of clickable thumbnails on the left, which updates the large primary image in the center. The right side is dedicated to product information, including a detailed list, price, size selection tiles, and color swatches. This design is ideal for products that require viewing from multiple angles or in different colors.",
    },
    {
      id: "product-details-5",
      title: "Product page with bottom gallery and navigation arrows",
      description:
        "A product detail layout featuring an interactive image gallery. The main product image is supported by a row of four thumbnails at the bottom for multi-angle viewing, along with directional arrows and a zoom icon for deep-dive inspection. The right-hand column maintains a clean hierarchy with product details, pricing, size selection tiles, and color swatches, providing an informative shopping interface.",
    },
    {
      id: "product-details-6",
      title: "Product page with centered hero and multi-column FAQ grid",
      description:
        "A comprehensive product layout featuring a centered hero image flanked by essential purchase controls like price, size selection tiles, and a button. The lower section of the page is dedicated to a high-density information area. This design uses expandable accordions for topics like shipping, returns, and terms, providing a one-stop-shop experience for all customer inquiries.",
    },
  ],
  "product-list": [
    {
      id: "product-list-1",
      title: "Product grid with header & action cards",
      description:
        "A clean e-commerce section featuring a left-aligned collection header and a four-column product grid. Each card includes a badge, high-quality product imagery, star ratings, pricing, and a brief description. The layout is finalized with a primary button for each product, designed to streamline the shopping experience through a clear and repetitive visual structure.",
    },
    {
      id: "product-list-2",
      title: "Centered header with product grid",
      description:
        "A balanced e-commerce section featuring a centered headline. The products are displayed in a clean four-column grid, where each card follows a vertical stack: high-quality product image, centered title, brief description, price, and a primary button. This minimalist approach removes distractions like ratings or badges, focusing entirely on product aesthetics and direct action.",
    },
    {
      id: "product-list-3",
      title: "Product card grid with color swatches",
      description:
        "A modern e-commerce grid featuring products housed in individual white cards with subtle borders. In addition to the badge, star ratings, and button, each card includes interactive color swatches for product customization. This layout is optimized for high-engagement retail, providing users with more options and a clear visual containment for each item.",
    },
    {
      id: "product-list-4",
      title: "Product grid with centered labels and color swatches",
      description:
        "A streamlined e-commerce layout featuring a centered collection header and a four-column grid of bordered product cards. Each card prioritizes clear information hierarchy: category badge, star rating, product title, and description, followed by prominent price labels and interactive color swatches. This design is optimized for brands that want to provide a detailed yet airy shopping experience.",
    },
    {
      id: "product-list-5",
      title: "Product grid with horizontal carousel",
      description:
        "A clean e-commerce section featuring a left-aligned collection header and a four-column product layout. Each item includes a badge, star rating, pricing, and a primary button. The distinctive feature is the inclusion of directional arrow buttons at the bottom-left, allowing users to scroll through a larger inventory within a single, space-efficient horizontal row.",
    },
  ],
  "rep-leaderboard": [
    {
      id: "rep-leaderboard-1",
      title: "Rep leaderboard",
      description: "Reps ranked by quota attainment with target markers.",
    },
  ],
  "revenue-vs-target": [
    {
      id: "revenue-vs-target-1",
      title: "Revenue vs target",
      description:
        "Closed revenue against target and forecast as a tick meter.",
    },
  ],
  "shopping-cart": [
    {
      id: "shopping-cart-1",
      title: "Overlay with itemized list and checkout",
      description:
        "A functional slide-out cart interface that appears as an overlay on the right side of the screen. It features a clear itemized list of added products, including thumbnail images, titles, brief descriptions, quantities, and prices. The layout is completed by a subtotal calculation at the bottom and a prominent button, providing a seamless transition from browsing to final purchase without leaving the current page.",
    },
    {
      id: "shopping-cart-2",
      title: "shopping cart page with order summary and promo section",
      description:
        "A comprehensive checkout page featuring a two-column layout. The larger left column displays a detailed list of cart items with quantity adjusters and removal options. The right column serves a sidebar containing a promo code input field and a breakdown of subtotal, shipping, and taxes. This design provides an overview of the order total, ensuring a frictionless transition to the final checkout stage.",
    },
    {
      id: "shopping-cart-3",
      title: "Centered shopping cart page with inline summary",
      description:
        "A streamlined and focused shopping cart layout where all elements are stacked in a single centered column. The page displays the list of items with full management controls (quantity and removal), followed directly by the promotional code input and the financial breakdown (subtotal, shipping, and taxes). This design minimizes eye travel and provides a clear, linear path toward the final checkout action.",
    },
    {
      id: "shopping-cart-4",
      title: "Triple-card cart layout with discount and summary",
      description:
        "A highly organized shopping cart page that utilizes three distinct white cards on a light gray background to separate functional areas. The main card on the left manages the product list and inventory controls. On the right, two smaller stacked cards isolate the Discount and Summary sections. This modular structure provides visual hierarchy and makes the information of the final checkout stage easy to digest.",
    },
  ],
  "social-proof": [
    {
      id: "social-proof-1",
      title: "Inline logo strip",
      description:
        "A minimal social proof pattern that presents partner or customer logos in a single horizontal row. It builds trust without interrupting flow, using uniform sizing and muted styling so the section supports the page rather than competing with primary content.",
    },
    {
      id: "social-proof-2",
      title: "Auto-scrolling logo marquee",
      description:
        "A horizontally scrolling logo strip that loops automatically. It adds motion and density without taking more vertical space. Good when you have lots of logos or want the section to feel more alive. Keep the speed slow and subtle so it reads as credibility, not decoration.",
    },
    {
      id: "social-proof-3",
      title: "Color logo strip",
      description:
        "A static row of full-color logos. Feels louder and more brand-forward than grayscale. Works best when the logos are well-known and visually consistent. Less subtle, but stronger at first glance.",
    },
    {
      id: "social-proof-4",
      title: "Inline trust statement",
      description:
        "A compact logo row paired with a short trust line. Very low visual weight and easy to drop between sections. Good when you want credibility without pulling attention away from the main content.",
    },
    {
      id: "social-proof-5",
      title: "Visual-led trust section",
      description:
        "A logo strip paired with a strong visual. Adds credibility while creating a clear visual break between sections. Best used when you want trust signals without relying on testimonials or copy-heavy proof.",
    },
    {
      id: "social-proof-6",
      title: "Structured grid, editorial feel",
      description:
        "Centered headline with a strict, even grid below. Strong symmetry, lots of white space, and clear hierarchy. Feels calm, credible, and deliberate. Works well when you want restraint and clarity over motion or visual noise.",
    },
  ],
  team: [
    {
      id: "team-1",
      title: "Centered team roster grid",
      description:
        "A centered section with a clear headline and supporting line, followed by an evenly spaced grid of profile tiles. The layout keeps attention on the faces, uses consistent alignment and spacing for quick scanning, and collapses cleanly into fewer columns on smaller screens without changing the overall structure.",
    },
    {
      id: "team-2",
      title: "Split intro with profile grid",
      description:
        "A two-column layout where a compact intro block anchors the section on the left while a dense, evenly spaced avatar grid fills the remaining width. The structure balances narrative and faces, maintains a strong visual rhythm, and adapts cleanly to a stacked list on smaller screens without changing the hierarchy.",
    },
    {
      id: "team-3",
      title: "Mixed-shape avatar mosaic",
      description: "Team 3 – Mixed-shape avatar mosaic",
    },
    {
      id: "team-4",
      title: "Lifestyle imagery with structured roster",
      description:
        "A split layout that pairs large, candid team photos with a clean, tabular roster below. The imagery adds warmth and context, while the list anchors the section with clear hierarchy and scannability, balancing human presence with structured information.",
    },
    {
      id: "team-5",
      title: "Editorial portrait cards",
      description:
        "A gallery-style layout built around large, consistent portrait cards with subtle overlays. Emphasizes visual uniformity and hierarchy, using generous spacing and minimal UI chrome to let imagery carry the section while still supporting clear identity and interaction.",
    },
  ],
  testimonials: [
    {
      id: "testimonials-1",
      title: "Single feature quote",
      description:
        "A centered, long-form testimonial designed to feel calm and authoritative. Uses generous whitespace, oversized quotation marks, and a single focal block to give the quote weight. Best suited for primary social proof moments where you want one voice to carry the section without visual noise.",
    },
    {
      id: "testimonials-2",
      title: "Centered quote with attribution focus",
      description:
        "A minimal, centered testimonial layout that tightens the hierarchy around the quote and author. Compared to Testimonial 1, this version reduces visual weight and brings the attribution closer to the content, making it feel more compact and versatile. Works well when you want strong social proof without the section dominating the page.",
    },
    {
      id: "testimonials-3",
      title: "Split quote with featured profile",
      description: "Testimonial 3 – Split quote with featured profile",
    },
    {
      id: "testimonials-4",
      title: "Image-led split with rating",
      description:
        "A bold split layout that gives equal weight to a large portrait and the testimonial copy. The oversized image anchors the section visually, while the quote, attribution, and star rating sit in a clean text column for clarity. Works best when you want testimonials to feel premium and emotive, not just informational.",
    },
    {
      id: "testimonials-6",
      title: "Split carousel with overlapping profile cards",
      description:
        "A split testimonial layout with the quote anchored in a static text column and a horizontal carousel of large profile cards running alongside it. The overlapping cards add depth and motion, while the fixed quote keeps the message readable and stable. Works well when you want strong visual presence without letting the imagery overpower the testimonial itself.",
    },
    {
      id: "testimonials-7",
      title: "Multi-profile grid with headline lead",
      description:
        "A testimonial layout that leads with a strong headline and brand marker, followed by a dense grid of profile cards. The structure shifts emphasis from a single quote to collective validation, using repetition and ratings to build credibility at scale. Best used when you want to show breadth of adoption rather than spotlight one individual voice.",
    },
    {
      id: "testimonials-8",
      title: "Branded quote with team strip",
      description:
        "A testimonial layout that anchors on a long-form quote with clear brand attribution, then reinforces credibility using a horizontal strip of individual profiles. The composition balances authority and social density, making it effective when you want a strong narrative supported by visible team adoption rather than a single spokesperson.",
    },
    {
      id: "testimonials-9",
      title: "Multi-segment case cards",
      description:
        "A testimonial layout built around small, self-contained story cards, each representing a different team or use case. The grid creates quick scanability while still allowing depth per card, making it well suited to showcasing breadth of adoption across industries rather than a single standout quote.",
    },
    {
      id: "testimonials-10",
      title: "Dense quote grid",
      description:
        "A compact testimonial layout that surfaces many short quotes at once using a uniform card grid. Designed for volume and credibility, it emphasizes breadth of feedback over individual storytelling, making it effective for scanning, comparison, and reinforcing widespread adoption.",
    },
    {
      id: "testimonials-11",
      title: "Editorial quote grid",
      description:
        "A structured testimonial layout that combines a clear section header with a multi-column grid of short quotes. It balances scannability and depth by presenting many voices at once, using consistent cards and subtle hierarchy to reinforce trust without relying on a single standout story.",
    },
  ],
  "top-landing-pages": [
    {
      id: "top-landing-pages-1",
      title: "Top landing pages",
      description: "Pages ranked by sessions with visitor share.",
    },
  ],
  "top-navigation": [
    {
      id: "top-navigation-1",
      title: "Left-aligned dropdown navigation",
      description:
        "A classic left-aligned top navigation with horizontal links and inline dropdown menus for larger screens. Primary actions are grouped on the right for clear visual separation. On smaller screens, the layout collapses into a full-height mobile menu with expandable sections, preserving hierarchy while keeping the interaction simple and familiar.",
    },
    {
      id: "top-navigation-2",
      title: "Centered primary navigation",
      description:
        "A center-aligned top navigation that places the primary links in the middle of the header, creating a more balanced, symmetrical layout. Dropdown menus open directly beneath each item on larger screens, while actions remain grouped to the right. On smaller screens, the navigation collapses into a vertical, full-height menu with expandable sections, keeping the structure clear while shifting focus to touch-friendly interaction.",
    },
    {
      id: "top-navigation-3",
      title: "Compact bar with progressive disclosure",
      description:
        "A compact top navigation that keeps the large-screen layout minimal and low-profile, with primary links arranged in a single horizontal bar. Dropdowns reveal richer, icon-led menus only when needed, keeping visual noise down by default. On smaller screens, the same structure expands into a stacked, panel-style menu with nested sections, preserving hierarchy while shifting emphasis to vertical scanning and tap targets.",
    },
    {
      id: "top-navigation-4",
      title: "Centered pill navigation with dropdown menu",
      description:
        "A centered top navigation where primary links sit inside a pill-style container, creating a strong visual anchor across large screens. Dropdown menus open from the center group to reveal secondary links in a compact panel. On small screens, the layout collapses into a full-height drawer with stacked links and clear primary actions, maintaining the same information structure while prioritizing tap comfort and readability.",
    },
  ],
  "traffic-by-channel": [
    {
      id: "traffic-by-channel-1",
      title: "Traffic by channel",
      description:
        "Total traffic with a segmented share bar and per-channel breakdown.",
    },
  ],
  "win-rate": [
    {
      id: "win-rate-1",
      title: "Win rate",
      description: "Win rate with stage-to-stage conversion bars.",
    },
  ],
}
