/**
 * Generates the per-library icon allowlists the icon loader imports.
 *
 * `create-icon-loader` looks an icon up by name. Doing that against a library's
 * barrel (`(await import("@tabler/icons-react"))[name]`) is a dynamic property
 * access, which no bundler can tree-shake — it has to ship every icon in the
 * library to satisfy one lookup, which cost ~0.5-1MB gzipped per library.
 *
 * These allowlists are static named re-exports, so the bundler keeps only the
 * icons this app actually asks for.
 *
 * Icon names come from `IconPlaceholder` props, e.g.
 *   <IconPlaceholder lucide="ChevronDownIcon" tabler="IconSelector" ... />
 *
 * Usage:
 *   pnpm generate:icon-allowlists
 *   pnpm generate:icon-allowlists --check   # fail if out of date
 */
import { readdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

const APP_ROOT = path.resolve(import.meta.dirname, "..")
const OUT_DIR = path.join(APP_ROOT, "vendor/v4/registry/icons")
const SCAN_DIRS = ["app", "components", "lib"].map((d) =>
  path.join(APP_ROOT, d)
)

const LIBRARIES = {
  lucide: "lucide-react",
  tabler: "@tabler/icons-react",
  hugeicons: "@hugeicons/core-free-icons",
  phosphor: "@phosphor-icons/react",
  remixicon: "@remixicon/react",
} as const

type LibraryName = keyof typeof LIBRARIES

async function* walk(dir: string): AsyncGenerator<string> {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      yield* walk(full)
    } else if (/\.tsx?$/.test(entry.name)) {
      yield full
    }
  }
}

function render(library: LibraryName, names: string[]): string {
  const pkg = LIBRARIES[library]
  return [
    `// Generated by scripts/generate-icon-allowlists.ts — do not edit by hand.`,
    `// Static re-exports so the bundler ships only the icons this app uses;`,
    `// a dynamic lookup against the ${pkg} barrel cannot be tree-shaken.`,
    ...names.map((name) => `export { ${name} } from "${pkg}"`),
    "",
  ].join("\n")
}

async function main() {
  const check = process.argv.includes("--check")
  const found: Record<LibraryName, Set<string>> = {
    lucide: new Set(),
    tabler: new Set(),
    hugeicons: new Set(),
    phosphor: new Set(),
    remixicon: new Set(),
  }

  for (const dir of SCAN_DIRS) {
    for await (const file of walk(dir)) {
      const source = await readFile(file, "utf8")
      for (const library of Object.keys(LIBRARIES) as LibraryName[]) {
        const pattern = new RegExp(`\\b${library}="([A-Za-z0-9_]+)"`, "g")
        for (const match of source.matchAll(pattern)) {
          found[library]!.add(match[1]!)
        }
      }
    }
  }

  let stale = false
  for (const library of Object.keys(LIBRARIES) as LibraryName[]) {
    const names = [...found[library]!].sort()
    const outPath = path.join(OUT_DIR, `__${library}__.ts`)
    const next = render(library, names)
    const current = await readFile(outPath, "utf8").catch(() => null)

    if (current === next) {
      console.log(`  ${library}: ${names.length} icons (unchanged)`)
      continue
    }

    stale = true
    if (check) {
      console.log(`  ${library}: ${names.length} icons (OUT OF DATE)`)
    } else {
      await writeFile(outPath, next)
      console.log(`  ${library}: ${names.length} icons (written)`)
    }
  }

  if (check && stale) {
    console.error(
      "\ngenerate-icon-allowlists: allowlists are out of date. Run `pnpm generate:icon-allowlists`."
    )
    process.exit(1)
  }
}

await main()
