/**
 * Writes the page builder's catalog from the shadcncraft blocks we have
 * imported:
 *
 * - lib/page-builder/variants.ts — the variants of each section and layout
 *   category, with shadcncraft's own title and description, which Jev reads
 *   to pick between them.
 * - components/page-builder/block-loaders.ts — one lazy component per block,
 *   so a built page downloads only the blocks on it.
 *
 *   pnpm generate:page-builder-catalog
 *
 * Run after `pnpm import:shadcncraft`. Needs the shadcncraft licence key, as
 * titles and descriptions come from the registry.
 */
import { execFileSync } from "node:child_process"
import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import path from "node:path"

import {
  LAYOUT_CATEGORIES,
  PAGE_SECTIONS,
} from "../lib/page-builder/sections"
import { viewShadcncraftItems } from "./lib/shadcncraft-registry"

const ROOT = path.resolve(import.meta.dirname, "..")
const BLOCKS = path.join(ROOT, "components/shadcncraft-examples/blocks")
const VARIANTS_OUT = path.join(ROOT, "lib/page-builder/variants.ts")
const LOADERS_OUT = path.join(ROOT, "components/page-builder/block-loaders.ts")
const BATCH = 25

/**
 * A layout slot takes part of a block, not all of it: an app shell is a
 * sidebar and a header around its content, and the header is its own
 * category, so the sidebar slot loads just the sidebar.
 */
const LOADER_OVERRIDES: Record<string, string> = {
  "app-shell": "components/app-sidebar",
}

type Block = {
  id: string
  section: string
  n: number
  /** Module under the block's folder, without extension. */
  file: string
  exportName: string
  isDefault: boolean
}

function readBlocks(): Block[] {
  const categories = new Set([
    ...PAGE_SECTIONS.map((section) => section.id),
    ...Object.values(LAYOUT_CATEGORIES).flatMap((slot) =>
      slot.map((category) => category.id)
    ),
  ])
  return readdirSync(BLOCKS)
    .map((id) => {
      const match = id.match(/^(.+)-(\d+)$/)
      if (!match || !categories.has(match[1])) return null
      const file = LOADER_OVERRIDES[match[1]] ?? "index"
      const source = readFileSync(path.join(BLOCKS, id, `${file}.tsx`), "utf8")
      const named = source.match(/^export function ([A-Z]\w*)/m)
      const fallback = source.match(/^export default function ([A-Z]\w*)/m)
      const exportName = named?.[1] ?? fallback?.[1]
      if (!exportName) throw new Error(`${id}: no exported component`)
      return {
        id,
        section: match[1],
        n: Number(match[2]),
        file,
        exportName,
        isDefault: !named,
      }
    })
    .filter((block): block is Block => block !== null)
    .sort((a, b) => a.section.localeCompare(b.section) || a.n - b.n)
}

/** "Hero 2 – Full-bleed background" → "Full-bleed background". */
function shortTitle(title: string | undefined, id: string): string {
  const after = title?.split(/\s[–-]\s+/).slice(1).join(" – ").trim()
  return after || title?.trim() || id
}

function main() {
  const blocks = readBlocks()
  const meta = new Map<string, { title?: string; description?: string }>()
  for (let i = 0; i < blocks.length; i += BATCH) {
    const ids = blocks.slice(i, i + BATCH).map((block) => block.id)
    for (const item of viewShadcncraftItems(ids)) meta.set(item.name, item)
  }

  const variants: Record<string, { id: string; title: string; description: string }[]> = {}
  for (const block of blocks) {
    const item = meta.get(block.id)
    ;(variants[block.section] ??= []).push({
      id: block.id,
      title: shortTitle(item?.title, block.id),
      description: (item?.description ?? "").replace(/\s+/g, " ").trim(),
    })
  }

  writeFileSync(
    VARIANTS_OUT,
    `// Generated by scripts/generate-page-builder-catalog.ts — do not edit by hand.
// Titles and descriptions are shadcncraft's own; Jev reads them to choose a
// variant, so a variant that keeps being misread is fixed upstream or here in
// the generator, not in this file.

export type PageBlockVariant = {
  id: string
  title: string
  description: string
}

export const PAGE_BLOCK_VARIANTS: Record<string, PageBlockVariant[]> = ${JSON.stringify(variants, null, 2)}
`
  )

  const loaders = blocks
    .map((block) => {
      const pick = block.isDefault ? "mod.default" : `mod.${block.exportName}`
      return `  "${block.id}": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/${block.id}${block.file === "index" ? "" : `/${block.file}`}").then(
      (mod) => ${pick}
    )
  ),`
    })
    .join("\n")

  writeFileSync(
    LOADERS_OUT,
    `// Generated by scripts/generate-page-builder-catalog.ts — do not edit by hand.
import type * as React from "react"
import dynamic from "next/dynamic"

/** One lazy component per block, so a page loads only the blocks on it. */
export const BLOCK_LOADERS: Record<string, React.ComponentType> = {
${loaders}
}
`
  )

  execFileSync("pnpm", ["exec", "prettier", "--write", VARIANTS_OUT, LOADERS_OUT], {
    cwd: ROOT,
    stdio: "ignore",
  })

  const missing = [
    ...PAGE_SECTIONS,
    ...Object.values(LAYOUT_CATEGORIES).flat(),
  ].filter((section) => !variants[section.id])
  console.log(
    `${blocks.length} blocks in ${Object.keys(variants).length} sections.` +
      (missing.length
        ? ` No blocks yet for: ${missing.map((s) => s.id).join(", ")}.`
        : "")
  )
}

main()
