/**
 * Generates `lib/generated-preview/catalog.ts` from the identifiers bound in
 * `GENERATED_PREVIEW_SCOPE`.
 *
 * The catalog is what the assistant prompt lists as available. Maintaining it
 * by hand let it drift out of step with the scope: it advertised top-level
 * names like `Drawer` without the subcomponents that actually make it usable,
 * so the model guessed (`DrawerBody`) and the preview died with a runtime
 * ReferenceError. Deriving it from the scope means the prompt can only name
 * identifiers that really resolve.
 *
 * Usage:
 *   pnpm generate:preview-catalog
 *   pnpm generate:preview-catalog --check   # fail if out of date
 */
import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"

const APP_ROOT = path.resolve(import.meta.dirname, "..")
const SCOPE_PATH = path.join(APP_ROOT, "lib/generated-preview/scope.tsx")
const CATALOG_PATH = path.join(APP_ROOT, "lib/generated-preview/catalog.ts")

/** Reads the shorthand keys of the `GENERATED_PREVIEW_SCOPE` object literal. */
export function extractScopeNames(source: string): string[] {
  const start = source.indexOf("export const GENERATED_PREVIEW_SCOPE")
  if (start === -1) {
    throw new Error("GENERATED_PREVIEW_SCOPE not found in scope.tsx")
  }
  const body = source.slice(source.indexOf("{", start) + 1)
  const names: string[] = []
  for (const line of body.split("\n")) {
    const match = /^\s{2}([A-Za-z_$][\w$]*),\s*$/.exec(line)
    if (match) {
      names.push(match[1]!)
    }
    if (/^}/.test(line)) break
  }
  return [...new Set(names)].sort()
}

function render(names: string[]): string {
  return [
    "// Generated by scripts/generate-preview-catalog.ts — do not edit by hand.",
    "// Every identifier bound in GENERATED_PREVIEW_SCOPE, so the assistant",
    "// prompt can only name components that actually resolve at render time.",
    "export const GENERATED_PREVIEW_COMPONENT_NAMES = [",
    ...names.map((name) => `  "${name}",`),
    "] as const",
    "",
  ].join("\n")
}

async function main() {
  const check = process.argv.includes("--check")
  const names = extractScopeNames(await readFile(SCOPE_PATH, "utf8"))
  const next = render(names)
  const current = await readFile(CATALOG_PATH, "utf8").catch(() => null)

  if (current === next) {
    console.log(`catalog: ${names.length} names (unchanged)`)
    return
  }

  if (check) {
    console.error(
      `catalog: ${names.length} names — OUT OF DATE. Run \`pnpm generate:preview-catalog\`.`
    )
    process.exit(1)
  }

  await writeFile(CATALOG_PATH, next)
  console.log(`catalog: ${names.length} names (written)`)
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  await main()
}
