import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored upstream source. `components/cn-ui` is regenerated by
    // `pnpm sync:cn-ui`, so lint fixes there are overwritten on the next sync.
    "components/cn-ui/**",
    "vendor/**",
  ]),
  {
    rules: {
      "react/jsx-curly-brace-presence": [
        "warn",
        {
          props: "never",
          children: "ignore",
        },
      ],
    },
  },
])

export default eslintConfig;
