// Generated by scripts/generate-page-builder-catalog.ts — do not edit by hand.
import type * as React from "react"
import dynamic from "next/dynamic"

/** One lazy component per block, so a page loads only the blocks on it. */
export const BLOCK_LOADERS: Record<string, React.ComponentType> = {
  "activity-feed-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/activity-feed-1").then(
      (mod) => mod.ActivityFeed1
    )
  ),
  "ai-insights-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/ai-insights-1").then(
      (mod) => mod.AiInsights1
    )
  ),
  "app-shell-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/app-shell-1/components/app-sidebar").then(
      (mod) => mod.AppSidebar
    )
  ),
  "app-shell-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/app-shell-2/components/app-sidebar").then(
      (mod) => mod.AppSidebar
    )
  ),
  "app-shell-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/app-shell-3/components/app-sidebar").then(
      (mod) => mod.AppSidebar
    )
  ),
  "app-shell-header-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/app-shell-header-1").then(
      (mod) => mod.AppShellHeader1
    )
  ),
  "app-shell-header-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/app-shell-header-2").then(
      (mod) => mod.AppShellHeader2
    )
  ),
  "app-shell-header-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/app-shell-header-3").then(
      (mod) => mod.AppShellHeader3
    )
  ),
  "app-shell-header-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/app-shell-header-4").then(
      (mod) => mod.AppShellHeader4
    )
  ),
  "app-shell-header-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/app-shell-header-5").then(
      (mod) => mod.AppShellHeader5
    )
  ),
  "attribution-breakdown-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/attribution-breakdown-1").then(
      (mod) => mod.AttributionBreakdown1
    )
  ),
  "benefits-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-1").then(
      (mod) => mod.Benefits1
    )
  ),
  "benefits-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-2").then(
      (mod) => mod.Benefits2
    )
  ),
  "benefits-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-3").then(
      (mod) => mod.Benefits3
    )
  ),
  "benefits-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-4").then(
      (mod) => mod.Benefits4
    )
  ),
  "benefits-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-5").then(
      (mod) => mod.Benefits5
    )
  ),
  "benefits-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-6").then(
      (mod) => mod.Benefits6
    )
  ),
  "benefits-7": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-7").then(
      (mod) => mod.Benefits7
    )
  ),
  "benefits-8": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-8").then(
      (mod) => mod.Benefits8
    )
  ),
  "benefits-9": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-9").then(
      (mod) => mod.Benefits9
    )
  ),
  "benefits-10": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-10").then(
      (mod) => mod.Benefits10
    )
  ),
  "benefits-11": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-11").then(
      (mod) => mod.Benefits11
    )
  ),
  "benefits-12": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-12").then(
      (mod) => mod.Benefits12
    )
  ),
  "benefits-13": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/benefits-13").then(
      (mod) => mod.Benefits13
    )
  ),
  "blog-listing-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/blog-listing-1").then(
      (mod) => mod.BlogListing1
    )
  ),
  "blog-listing-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/blog-listing-2").then(
      (mod) => mod.BlogListing2
    )
  ),
  "blog-listing-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/blog-listing-3").then(
      (mod) => mod.BlogListing3
    )
  ),
  "blog-listing-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/blog-listing-4").then(
      (mod) => mod.BlogListing4
    )
  ),
  "campaign-performance-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/campaign-performance-1").then(
      (mod) => mod.CampaignPerformance1
    )
  ),
  "careers-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/careers-1").then(
      (mod) => mod.Careers1
    )
  ),
  "careers-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/careers-2").then(
      (mod) => mod.Careers2
    )
  ),
  "careers-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/careers-3").then(
      (mod) => mod.Careers3
    )
  ),
  "careers-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/careers-4").then(
      (mod) => mod.Careers4
    )
  ),
  "careers-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/careers-5").then(
      (mod) => mod.Careers5
    )
  ),
  "channel-performance-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/channel-performance-1").then(
      (mod) => mod.ChannelPerformance1
    )
  ),
  "checkout-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/checkout-1").then(
      (mod) => mod.Checkout1
    )
  ),
  "checkout-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/checkout-2").then(
      (mod) => mod.Checkout2
    )
  ),
  "checkout-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/checkout-3").then(
      (mod) => mod.Checkout3
    )
  ),
  "contact-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-1").then(
      (mod) => mod.Contact1
    )
  ),
  "contact-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-2").then(
      (mod) => mod.Contact2
    )
  ),
  "contact-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-3").then(
      (mod) => mod.Contact3
    )
  ),
  "contact-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-4").then(
      (mod) => mod.Contact4
    )
  ),
  "contact-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-5").then(
      (mod) => mod.Contact5
    )
  ),
  "contact-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-6").then(
      (mod) => mod.Contact6
    )
  ),
  "contact-7": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-7").then(
      (mod) => mod.Contact7
    )
  ),
  "contact-8": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-8").then(
      (mod) => mod.Contact8
    )
  ),
  "contact-9": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-9").then(
      (mod) => mod.Contact9
    )
  ),
  "contact-11": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/contact-11").then(
      (mod) => mod.Contact11
    )
  ),
  "cost-per-acquisition-trend-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cost-per-acquisition-trend-1").then(
      (mod) => mod.CostPerAcquisitionTrend1
    )
  ),
  "cta-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cta-1").then(
      (mod) => mod.CTA1
    )
  ),
  "cta-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cta-2").then(
      (mod) => mod.CTA2
    )
  ),
  "cta-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cta-3").then(
      (mod) => mod.CTA3
    )
  ),
  "cta-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cta-4").then(
      (mod) => mod.CTA4
    )
  ),
  "cta-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cta-5").then(
      (mod) => mod.CTA5
    )
  ),
  "cta-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cta-6").then(
      (mod) => mod.CTA6
    )
  ),
  "cta-7": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cta-7").then(
      (mod) => mod.CTA7
    )
  ),
  "cta-8": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/cta-8").then(
      (mod) => mod.CTA8
    )
  ),
  "customer-health-score-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/customer-health-score-1").then(
      (mod) => mod.CustomerHealthScore1
    )
  ),
  "deal-velocity-by-segment-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/deal-velocity-by-segment-1").then(
      (mod) => mod.DealVelocityBySegment1
    )
  ),
  "deals-table-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/deals-table-1").then(
      (mod) => mod.DealsTable1
    )
  ),
  "engagement-by-day-hour-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/engagement-by-day-hour-1").then(
      (mod) => mod.EngagementByDayHour1
    )
  ),
  "faqs-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/faqs-1").then(
      (mod) => mod.FAQs1
    )
  ),
  "faqs-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/faqs-2").then(
      (mod) => mod.FAQs2
    )
  ),
  "faqs-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/faqs-3").then(
      (mod) => mod.FAQs3
    )
  ),
  "faqs-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/faqs-4").then(
      (mod) => mod.Faqs4
    )
  ),
  "footer-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/footer-1").then(
      (mod) => mod.Footer1
    )
  ),
  "footer-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/footer-2").then(
      (mod) => mod.Footer2
    )
  ),
  "footer-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/footer-3").then(
      (mod) => mod.Footer3
    )
  ),
  "footer-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/footer-4").then(
      (mod) => mod.Footer4
    )
  ),
  "goal-progress-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/goal-progress-1").then(
      (mod) => mod.GoalProgress1
    )
  ),
  "hero-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-1").then(
      (mod) => mod.Hero1
    )
  ),
  "hero-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-2").then(
      (mod) => mod.Hero2
    )
  ),
  "hero-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-3").then(
      (mod) => mod.Hero3
    )
  ),
  "hero-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-4").then(
      (mod) => mod.Hero4
    )
  ),
  "hero-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-5").then(
      (mod) => mod.Hero5
    )
  ),
  "hero-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-6").then(
      (mod) => mod.Hero6
    )
  ),
  "hero-7": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-7").then(
      (mod) => mod.Hero7
    )
  ),
  "hero-8": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-8").then(
      (mod) => mod.Hero8
    )
  ),
  "hero-9": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-9").then(
      (mod) => mod.Hero9
    )
  ),
  "hero-10": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-10").then(
      (mod) => mod.Hero10
    )
  ),
  "hero-time-series-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/hero-time-series-1").then(
      (mod) => mod.HeroTimeSeries1
    )
  ),
  "lead-to-customer-funnel-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/lead-to-customer-funnel-1").then(
      (mod) => mod.LeadToCustomerFunnel1
    )
  ),
  "leads-by-region-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/leads-by-region-1").then(
      (mod) => mod.LeadsByRegion1
    )
  ),
  "marketing-funnel-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/marketing-funnel-1").then(
      (mod) => mod.MarketingFunnel1
    )
  ),
  "metric-cards-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/metric-cards-1").then(
      (mod) => mod.MetricCards1
    )
  ),
  "metrics-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/metrics-1").then(
      (mod) => mod.Metrics1
    )
  ),
  "metrics-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/metrics-2").then(
      (mod) => mod.Metrics2
    )
  ),
  "metrics-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/metrics-3").then(
      (mod) => mod.Metrics3
    )
  ),
  "metrics-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/metrics-4").then(
      (mod) => mod.Metrics4
    )
  ),
  "metrics-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/metrics-5").then(
      (mod) => mod.Metrics5
    )
  ),
  "metrics-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/metrics-6").then(
      (mod) => mod.Metrics6
    )
  ),
  "metrics-7": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/metrics-7").then(
      (mod) => mod.Metrics7
    )
  ),
  "newsletter-signup-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/newsletter-signup-1").then(
      (mod) => mod.NewsletterSignup1
    )
  ),
  "newsletter-signup-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/newsletter-signup-2").then(
      (mod) => mod.NewsletterSignup2
    )
  ),
  "newsletter-signup-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/newsletter-signup-3").then(
      (mod) => mod.NewsletterSignup3
    )
  ),
  "newsletter-signup-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/newsletter-signup-4").then(
      (mod) => mod.NewsletterSignup4
    )
  ),
  "newsletter-signup-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/newsletter-signup-5").then(
      (mod) => mod.NewsletterSignup5
    )
  ),
  "paid-media-allocation-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/paid-media-allocation-1").then(
      (mod) => mod.PaidMediaAllocation1
    )
  ),
  "pipeline-by-stage-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/pipeline-by-stage-1").then(
      (mod) => mod.PipelineByStage1
    )
  ),
  "pricing-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/pricing-1").then(
      (mod) => mod.Pricing1
    )
  ),
  "pricing-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/pricing-2").then(
      (mod) => mod.Pricing2
    )
  ),
  "pricing-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/pricing-3").then(
      (mod) => mod.Pricing3
    )
  ),
  "pricing-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/pricing-4").then(
      (mod) => mod.Pricing4
    )
  ),
  "pricing-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/pricing-5").then(
      (mod) => mod.Pricing5
    )
  ),
  "pricing-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/pricing-6").then(
      (mod) => mod.Pricing6
    )
  ),
  "pricing-7": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/pricing-7").then(
      (mod) => mod.Pricing7
    )
  ),
  "product-category-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-category-1").then(
      (mod) => mod.ProductCategory1
    )
  ),
  "product-category-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-category-2").then(
      (mod) => mod.ProductCategory2
    )
  ),
  "product-category-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-category-3").then(
      (mod) => mod.ProductCategory3
    )
  ),
  "product-category-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-category-4").then(
      (mod) => mod.ProductCategory4
    )
  ),
  "product-category-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-category-5").then(
      (mod) => mod.ProductCategory5
    )
  ),
  "product-details-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-details-1").then(
      (mod) => mod.default
    )
  ),
  "product-details-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-details-2").then(
      (mod) => mod.ProductDetails2
    )
  ),
  "product-details-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-details-3").then(
      (mod) => mod.default
    )
  ),
  "product-details-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-details-4").then(
      (mod) => mod.default
    )
  ),
  "product-details-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-details-5").then(
      (mod) => mod.default
    )
  ),
  "product-details-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-details-6").then(
      (mod) => mod.default
    )
  ),
  "product-list-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-list-1").then(
      (mod) => mod.default
    )
  ),
  "product-list-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-list-2").then(
      (mod) => mod.default
    )
  ),
  "product-list-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-list-3").then(
      (mod) => mod.ProductList3
    )
  ),
  "product-list-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-list-4").then(
      (mod) => mod.default
    )
  ),
  "product-list-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/product-list-5").then(
      (mod) => mod.default
    )
  ),
  "rep-leaderboard-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/rep-leaderboard-1").then(
      (mod) => mod.RepLeaderboard1
    )
  ),
  "revenue-vs-target-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/revenue-vs-target-1").then(
      (mod) => mod.RevenueVsTarget1
    )
  ),
  "shopping-cart-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/shopping-cart-1").then(
      (mod) => mod.ShoppingCart1
    )
  ),
  "shopping-cart-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/shopping-cart-2").then(
      (mod) => mod.ShoppingCart2
    )
  ),
  "shopping-cart-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/shopping-cart-3").then(
      (mod) => mod.ShoppingCart3
    )
  ),
  "shopping-cart-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/shopping-cart-4").then(
      (mod) => mod.ShoppingCart4
    )
  ),
  "social-proof-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/social-proof-1").then(
      (mod) => mod.SocialProof1
    )
  ),
  "social-proof-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/social-proof-2").then(
      (mod) => mod.SocialProof2
    )
  ),
  "social-proof-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/social-proof-3").then(
      (mod) => mod.SocialProof3
    )
  ),
  "social-proof-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/social-proof-4").then(
      (mod) => mod.SocialProof4
    )
  ),
  "social-proof-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/social-proof-5").then(
      (mod) => mod.SocialProof5
    )
  ),
  "social-proof-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/social-proof-6").then(
      (mod) => mod.SocialProof6
    )
  ),
  "team-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/team-1").then(
      (mod) => mod.Team1
    )
  ),
  "team-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/team-2").then(
      (mod) => mod.Team2
    )
  ),
  "team-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/team-3").then(
      (mod) => mod.Team3
    )
  ),
  "team-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/team-4").then(
      (mod) => mod.Team4
    )
  ),
  "team-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/team-5").then(
      (mod) => mod.Team5
    )
  ),
  "testimonials-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-1").then(
      (mod) => mod.Testimonials1
    )
  ),
  "testimonials-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-2").then(
      (mod) => mod.Testimonials2
    )
  ),
  "testimonials-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-3").then(
      (mod) => mod.Testimonials3
    )
  ),
  "testimonials-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-4").then(
      (mod) => mod.Testimonials4
    )
  ),
  "testimonials-6": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-6").then(
      (mod) => mod.Testimonials6
    )
  ),
  "testimonials-7": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-7").then(
      (mod) => mod.Testimonials7
    )
  ),
  "testimonials-8": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-8").then(
      (mod) => mod.Testimonials8
    )
  ),
  "testimonials-9": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-9").then(
      (mod) => mod.Testimonials9
    )
  ),
  "testimonials-10": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-10").then(
      (mod) => mod.Testimonials10
    )
  ),
  "testimonials-11": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/testimonials-11").then(
      (mod) => mod.Testimonials11
    )
  ),
  "top-landing-pages-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/top-landing-pages-1").then(
      (mod) => mod.TopLandingPages1
    )
  ),
  "top-navigation-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/top-navigation-1").then(
      (mod) => mod.TopNavigation1
    )
  ),
  "top-navigation-2": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/top-navigation-2").then(
      (mod) => mod.TopNavigation2
    )
  ),
  "top-navigation-3": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/top-navigation-3").then(
      (mod) => mod.TopNavigation3
    )
  ),
  "top-navigation-4": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/top-navigation-4").then(
      (mod) => mod.TopNavigation4
    )
  ),
  "top-navigation-5": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/top-navigation-5").then(
      (mod) => mod.TopNavigation5
    )
  ),
  "traffic-by-channel-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/traffic-by-channel-1").then(
      (mod) => mod.TrafficByChannel1
    )
  ),
  "win-rate-1": dynamic(() =>
    import("@/components/shadcncraft-examples/blocks/win-rate-1").then(
      (mod) => mod.WinRate1
    )
  ),
}
